---
version: '2'
services:
  mysql80:
      image: mysql:8.0.25
      command: [ "--server-id=1", "--log-bin=/var/lib/mysql/mysql-bin.log", "--binlog-format=row", "--default-authentication-plugin=mysql_native_password"]
      networks:
        default:
          aliases:
            - mysql80
      environment:
        MYSQL_ROOT_PASSWORD: numtel
